name: Hola mundo Actions GH

on:
  push:
    branches:
      - main

jobs:
  hola_mundo:
    name: Imprimir Hola mundo
    runs-on: ubuntu-latest
    steps:
      - name: Revisar el repo
        uses: actions/checkout@v2

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Ejecutar codigo de python
        run: python3 app.py
