name: github_actions_1
on:
    push:
        branches:
            - main

jobs:
    first-action:
        name: Execute_first_action
        runs-on: ubuntu-latest

        steps:
            - name: Execute_first_action
            run: echo "Hola Mundo"